name: 'lastfm_dbt'
version: '1.0.0'
config-version: 2

profile: 'lastfm_dbt'

model-paths:  ["models"]
macro-paths:  ["macros"]
test-paths:   ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lastfm_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
